SELECT AU_ID, COUNT(BOOK_NUM) AS "BOOKS WRITTEN"
FROM WRITES
GROUP BY AU_ID
ORDER BY COUNT(BOOK_NUM) DESC, AU_ID;








SELECT * FROM BOOK;
SELECT * FROM CHECKOUT;

SELECT BOOK_NUM, BOOK_TITLE, COUNT(CHECK_NUM) AS "TIMES CHECKED OUT"
FROM BOOK
     LEFT OUTER JOIN CHECKOUT USING (BOOK_NUM)
GROUP BY BOOK_NUM
ORDER BY COUNT(CHECK_NUM) DESC, BOOK_TITLE;









SELECT * FROM BOOK;
SELECT * FROM CHECKOUT;

SELECT BOOK_NUM, BOOK_TITLE, COUNT(CHECK_NUM) AS "TIMES CHECKED OUT"
FROM BOOK JOIN CHECKOUT USING (BOOK_NUM)
GROUP BY BOOK_NUM
HAVING COUNT(CHECK_NUM) > 5
ORDER BY COUNT(CHECK_NUM) DESC, BOOK_TITLE;